[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
tag_format = "v$version"
version_files = [
    "package.json:version",
    "src-tauri/Cargo.toml:version",
    "src-tauri/tauri.conf.json:version",
    "src/components/Settings.tsx:APP_VERSION",
]
update_changelog_on_bump = true
